# https://doc.rust-lang.org/stable/clippy/index.html

doc-valid-idents = [
    "KiwiRail",
    "R9K",
    "SmarTrak",
    "OpenTelemetry",
]
allowed-duplicate-crates = [
    "getrandom",
    "hashbrown",
    "rand",
    "rand_chacha",
    "rand_core",
    "rustls-webpki",
    "thiserror",
    "thiserror-impl",
    "wasi",
    "webpki-roots",
    "windows-sys",
]