# https://doc.rust-lang.org/stable/clippy/index.html

doc-valid-idents = [
    "KiwiRail",
    "R9K",
    "SmarTrak",
    "OpenTelemetry",
]
allowed-duplicate-crates = [
    "embedded-io",
    "getrandom",
    "hashbrown",
    "linux-raw-sys",
    "rand",
    "rand_chacha",
    "rand_core",
    "rustix",
    "rustls",
    "rustls-webpki",
    "thiserror",
    "thiserror-impl",
    "tokio-rustls",
    "wasi",
    "webpki-roots",
    "windows-link",
    "windows-result",
    "windows-strings",
    "windows-sys",
    "windows-targets",
    "windows_aarch64_gnullvm",
    "windows_aarch64_msvc",
    "windows_i686_gnu",
    "windows_i686_gnullvm",
    "windows_i686_msvc",
    "windows_x86_64_gnu",
    "windows_x86_64_gnullvm",
    "windows_x86_64_msvc",
]
