
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[[exemptions.addr2line]]
version = "0.17.0"
criteria = "safe-to-deploy"

[[exemptions.async-nats]]
version = "0.44.2"
criteria = "safe-to-deploy"

[[exemptions.axum]]
version = "0.8.6"
criteria = "safe-to-deploy"

[[exemptions.axum-core]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.base64ct]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.bincode]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.bincode_derive]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.2.44"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.42"
criteria = "safe-to-deploy"

[[exemptions.const-hex]]
version = "1.17.0"
criteria = "safe-to-deploy"

[[exemptions.const-oid]]
version = "0.9.6"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek]]
version = "4.1.0"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek-derive]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.data-encoding]]
version = "2.9.0"
criteria = "safe-to-deploy"

[[exemptions.der]]
version = "0.7.8"
criteria = "safe-to-deploy"

[[exemptions.deranged]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.ed25519]]
version = "2.2.1"
criteria = "safe-to-deploy"

[[exemptions.ed25519-dalek]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.fallible-iterator]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.5"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.hyper-rustls]]
version = "0.27.5"
criteria = "safe-to-deploy"

[[exemptions.hyper-timeout]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.iri-string]]
version = "0.7.8"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.10.3"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.82"
criteria = "safe-to-deploy"

[[exemptions.lru-slab]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.matchit]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.maybe-owned]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.nkeys]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.nu-ansi-term]]
version = "0.50.3"
criteria = "safe-to-deploy"

[[exemptions.nuid]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.36.0"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.3"
criteria = "safe-to-deploy"

[[exemptions.openssl]]
version = "0.10.74"
criteria = "safe-to-deploy"

[[exemptions.openssl-sys]]
version = "0.9.110"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry-http]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry-otlp]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry-proto]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry_sdk]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.pem-rfc7468]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.1.10"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.1.10"
criteria = "safe-to-deploy"

[[exemptions.pkcs8]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.pkg-config]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.portable-atomic]]
version = "1.11.1"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.21"
criteria = "safe-to-deploy"

[[exemptions.proptest]]
version = "1.9.0"
criteria = "safe-to-deploy"

[[exemptions.prost]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.prost-derive]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.quick-xml]]
version = "0.38.3"
criteria = "safe-to-deploy"

[[exemptions.quinn]]
version = "0.11.9"
criteria = "safe-to-deploy"

[[exemptions.quinn-proto]]
version = "0.11.13"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "5.3.0"
criteria = "safe-to-deploy"

[[exemptions.rand_xorshift]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.17.14"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.22.4"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.23.34"
criteria = "safe-to-deploy"

[[exemptions.rustls-native-certs]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.rustls-pemfile]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.rustls-pki-types]]
version = "1.13.0"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.102.8"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.103.8"
criteria = "safe-to-deploy"

[[exemptions.schannel]]
version = "0.1.28"
criteria = "safe-to-deploy"

[[exemptions.security-framework]]
version = "2.11.1"
criteria = "safe-to-deploy"

[[exemptions.security-framework-sys]]
version = "2.15.0"
criteria = "safe-to-deploy"

[[exemptions.semver]]
version = "1.0.27"
criteria = "safe-to-deploy"

[[exemptions.serde_nanos]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.serde_urlencoded]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.signatory]]
version = "0.27.1"
criteria = "safe-to-deploy"

[[exemptions.spki]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.stable_deref_trait]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.sync_wrapper]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.system-configuration]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.system-configuration-sys]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.3.0"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.44"
criteria = "safe-to-deploy"

[[exemptions.time-core]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.time-macros]]
version = "0.2.24"
criteria = "safe-to-deploy"

[[exemptions.tinyvec]]
version = "1.10.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-rustls]]
version = "0.25.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-rustls]]
version = "0.26.4"
criteria = "safe-to-deploy"

[[exemptions.tokio-websockets]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.tonic]]
version = "0.14.2"
criteria = "safe-to-deploy"

[[exemptions.tonic-prost]]
version = "0.14.2"
criteria = "safe-to-deploy"

[[exemptions.tower-layer]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tracing-opentelemetry]]
version = "0.32.0"
criteria = "safe-to-deploy"

[[exemptions.tryhard]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.19.0"
criteria = "safe-to-deploy"

[[exemptions.unarray]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.unty]]
version = "0.0.4"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.virtue]]
version = "0.0.18"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.105"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-futures]]
version = "0.4.55"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.105"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.105"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.82"
criteria = "safe-to-deploy"

[[exemptions.web-time]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.webpki-roots]]
version = "0.26.11"
criteria = "safe-to-deploy"

[[exemptions.webpki-roots]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.8.27"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.8.27"
criteria = "safe-to-deploy"
