
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[[exemptions.chrono]]
version = "0.4.42"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.io-uring]]
version = "0.7.10"
criteria = "safe-to-run"

[[exemptions.js-sys]]
version = "0.3.81"
criteria = "safe-to-deploy"

[[exemptions.nu-ansi-term]]
version = "0.50.3"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.36.0"
criteria = "safe-to-run"

[[exemptions.once_cell]]
version = "1.21.3"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry_sdk]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.21"
criteria = "safe-to-deploy"

[[exemptions.quick-xml]]
version = "0.38.3"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.41"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "5.3.0"
criteria = "safe-to-deploy"

[[exemptions.semver]]
version = "1.0.27"
criteria = "safe-to-deploy"

[[exemptions.tracing-opentelemetry]]
version = "0.32.0"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.104"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.104"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.104"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.104"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.104"
criteria = "safe-to-deploy"

[[exemptions.web-time]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.8.27"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.8.27"
criteria = "safe-to-deploy"
