
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.cranelift-assembler-x64]
audit-as-crates-io = true

[policy.cranelift-assembler-x64-meta]
audit-as-crates-io = true

[policy.cranelift-bforest]
audit-as-crates-io = true

[policy.cranelift-bitset]
audit-as-crates-io = true

[policy.cranelift-codegen]
audit-as-crates-io = true

[policy.cranelift-codegen-meta]
audit-as-crates-io = true

[policy.cranelift-codegen-shared]
audit-as-crates-io = true

[policy.cranelift-control]
audit-as-crates-io = true

[policy.cranelift-entity]
audit-as-crates-io = true

[policy.cranelift-frontend]
audit-as-crates-io = true

[policy.cranelift-isle]
audit-as-crates-io = true

[policy.cranelift-native]
audit-as-crates-io = true

[policy.cranelift-srcgen]
audit-as-crates-io = true

[policy.pulley-interpreter]
audit-as-crates-io = true

[policy.pulley-macros]
audit-as-crates-io = true

[policy.wasmtime]
audit-as-crates-io = true

[policy.wasmtime-environ]
audit-as-crates-io = true

[policy.wasmtime-internal-component-macro]
audit-as-crates-io = true

[policy.wasmtime-internal-component-util]
audit-as-crates-io = true

[policy.wasmtime-internal-cranelift]
audit-as-crates-io = true

[policy.wasmtime-internal-fiber]
audit-as-crates-io = true

[policy.wasmtime-internal-jit-debug]
audit-as-crates-io = true

[policy.wasmtime-internal-jit-icache-coherence]
audit-as-crates-io = true

[policy.wasmtime-internal-math]
audit-as-crates-io = true

[policy.wasmtime-internal-slab]
audit-as-crates-io = true

[policy.wasmtime-internal-unwinder]
audit-as-crates-io = true

[policy.wasmtime-internal-versioned-export-macros]
audit-as-crates-io = true

[policy.wasmtime-internal-winch]
audit-as-crates-io = true

[policy.wasmtime-internal-wit-bindgen]
audit-as-crates-io = true

[policy.wasmtime-wasi]
audit-as-crates-io = true

[policy.wasmtime-wasi-http]
audit-as-crates-io = true

[policy.wasmtime-wasi-io]
audit-as-crates-io = true

[policy.wiggle]
audit-as-crates-io = true

[policy.wiggle-generate]
audit-as-crates-io = true

[policy.wiggle-macro]
audit-as-crates-io = true

[policy.winch-codegen]
audit-as-crates-io = true

[[exemptions.addr2line]]
version = "0.17.0"
criteria = "safe-to-deploy"

[[exemptions.axum]]
version = "0.8.7"
criteria = "safe-to-deploy"

[[exemptions.axum-core]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.axum-macros]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.base64ct]]
version = "1.8.1"
criteria = "safe-to-deploy"

[[exemptions.bincode]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.bincode_derive]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.2.49"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.42"
criteria = "safe-to-deploy"

[[exemptions.chrono-tz]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.const-hex]]
version = "1.17.0"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.cranelift-assembler-x64]]
version = "0.127.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.cranelift-assembler-x64-meta]]
version = "0.127.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.cranelift-bforest]]
version = "0.127.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.cranelift-bitset]]
version = "0.127.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.cranelift-codegen]]
version = "0.127.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.cranelift-codegen-meta]]
version = "0.127.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.cranelift-codegen-shared]]
version = "0.127.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.cranelift-control]]
version = "0.127.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.cranelift-entity]]
version = "0.127.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.cranelift-frontend]]
version = "0.127.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.cranelift-isle]]
version = "0.127.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.cranelift-native]]
version = "0.127.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.cranelift-srcgen]]
version = "0.127.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-deque]]
version = "0.8.6"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-epoch]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.8"
criteria = "safe-to-deploy"

[[exemptions.crypto-common]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.darling]]
version = "0.21.3"
criteria = "safe-to-deploy"

[[exemptions.darling_core]]
version = "0.21.3"
criteria = "safe-to-deploy"

[[exemptions.darling_macro]]
version = "0.20.11"
criteria = "safe-to-deploy"

[[exemptions.dashmap]]
version = "5.5.3"
criteria = "safe-to-deploy"

[[exemptions.deranged]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.diff]]
version = "0.1.13"
criteria = "safe-to-run"

[[exemptions.digest]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.fallible-iterator]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.find-msvc-tools]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.fromenv]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.fromenv-derive]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.5"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.14.2"
criteria = "safe-to-deploy"

[[exemptions.hyper-rustls]]
version = "0.27.5"
criteria = "safe-to-deploy"

[[exemptions.hyper-timeout]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.icu_properties]]
version = "2.1.2"
criteria = "safe-to-deploy"

[[exemptions.icu_properties_data]]
version = "2.1.2"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.iri-string]]
version = "0.7.9"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.10.3"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.83"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.29"
criteria = "safe-to-deploy"

[[exemptions.lru-slab]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.matchit]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.maybe-owned]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.oauth2]]
version = "5.0.0"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.36.0"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.3"
criteria = "safe-to-deploy"

[[exemptions.openssl]]
version = "0.10.75"
criteria = "safe-to-deploy"

[[exemptions.openssl-sys]]
version = "0.9.111"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry-http]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry-otlp]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry-proto]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry_sdk]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.1.10"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.1.10"
criteria = "safe-to-deploy"

[[exemptions.pkg-config]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.21"
criteria = "safe-to-deploy"

[[exemptions.pretty_assertions]]
version = "1.4.1"
criteria = "safe-to-run"

[[exemptions.proptest]]
version = "1.9.0"
criteria = "safe-to-deploy"

[[exemptions.prost]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.prost-derive]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.pulley-interpreter]]
version = "40.0.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.pulley-macros]]
version = "40.0.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.quick-xml]]
version = "0.38.4"
criteria = "safe-to-deploy"

[[exemptions.quinn]]
version = "0.11.9"
criteria = "safe-to-deploy"

[[exemptions.quinn-proto]]
version = "0.11.13"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "5.3.0"
criteria = "safe-to-deploy"

[[exemptions.rand_xorshift]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.5.18"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.17.14"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.22.4"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.23.35"
criteria = "safe-to-deploy"

[[exemptions.rustls-pki-types]]
version = "1.13.1"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.102.8"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.103.8"
criteria = "safe-to-deploy"

[[exemptions.schannel]]
version = "0.1.28"
criteria = "safe-to-deploy"

[[exemptions.security-framework]]
version = "2.11.1"
criteria = "safe-to-deploy"

[[exemptions.security-framework-sys]]
version = "2.15.0"
criteria = "safe-to-deploy"

[[exemptions.semver]]
version = "1.0.27"
criteria = "safe-to-deploy"

[[exemptions.serde_urlencoded]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.siphasher]]
version = "0.3.10"
criteria = "safe-to-deploy"

[[exemptions.stable_deref_trait]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.sync_wrapper]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.system-configuration]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.system-configuration-sys]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.3.0"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.44"
criteria = "safe-to-deploy"

[[exemptions.time-core]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.tinyvec]]
version = "1.10.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-rustls]]
version = "0.25.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-rustls]]
version = "0.26.4"
criteria = "safe-to-deploy"

[[exemptions.tonic]]
version = "0.14.2"
criteria = "safe-to-deploy"

[[exemptions.tonic-prost]]
version = "0.14.2"
criteria = "safe-to-deploy"

[[exemptions.tower-layer]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.43"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.31"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.35"
criteria = "safe-to-deploy"

[[exemptions.tracing-opentelemetry]]
version = "0.32.0"
criteria = "safe-to-deploy"

[[exemptions.tracing-subscriber]]
version = "0.3.22"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.19.0"
criteria = "safe-to-deploy"

[[exemptions.unarray]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.unty]]
version = "0.0.4"
criteria = "safe-to-deploy"

[[exemptions.urlencoding]]
version = "2.1.3"
criteria = "safe-to-deploy"

[[exemptions.uuid]]
version = "1.19.0"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.virtue]]
version = "0.0.18"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.106"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-futures]]
version = "0.4.56"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.106"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.106"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.106"
criteria = "safe-to-deploy"

[[exemptions.wasmtime]]
version = "40.0.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.wasmtime-environ]]
version = "40.0.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.wasmtime-internal-component-macro]]
version = "40.0.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.wasmtime-internal-component-util]]
version = "40.0.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.wasmtime-internal-cranelift]]
version = "40.0.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.wasmtime-internal-fiber]]
version = "40.0.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.wasmtime-internal-jit-debug]]
version = "40.0.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.wasmtime-internal-jit-icache-coherence]]
version = "40.0.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.wasmtime-internal-math]]
version = "40.0.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.wasmtime-internal-slab]]
version = "40.0.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.wasmtime-internal-unwinder]]
version = "40.0.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.wasmtime-internal-versioned-export-macros]]
version = "40.0.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.wasmtime-internal-winch]]
version = "40.0.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.wasmtime-internal-wit-bindgen]]
version = "40.0.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.wasmtime-wasi]]
version = "40.0.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.wasmtime-wasi-http]]
version = "40.0.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.wasmtime-wasi-io]]
version = "40.0.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.83"
criteria = "safe-to-deploy"

[[exemptions.web-time]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.webpki-roots]]
version = "0.26.11"
criteria = "safe-to-deploy"

[[exemptions.webpki-roots]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.wiggle]]
version = "40.0.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.wiggle-generate]]
version = "40.0.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.wiggle-macro]]
version = "40.0.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.winch-codegen]]
version = "40.0.0@git:fadd22ab5098f28f8318ca3c20fe59fa9f93baec"
criteria = "safe-to-deploy"

[[exemptions.wit-bindgen]]
version = "0.48.1"
criteria = "safe-to-deploy"

[[exemptions.wit-bindgen-core]]
version = "0.48.1"
criteria = "safe-to-deploy"

[[exemptions.wit-bindgen-rust]]
version = "0.48.1"
criteria = "safe-to-deploy"

[[exemptions.wit-bindgen-rust-macro]]
version = "0.48.1"
criteria = "safe-to-deploy"

[[exemptions.yansi]]
version = "1.0.1"
criteria = "safe-to-run"

[[exemptions.zerocopy]]
version = "0.8.31"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.8.31"
criteria = "safe-to-deploy"
