name: Publish Release

on:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: augentic/pipeline/.github/workflows/ci.yaml@main
    secrets:
      CARGO_REGISTRIES_CREDIBIL_TOKEN: ${{ secrets.CARGO_REGISTRIES_CREDIBIL_TOKEN }}

  publish:
    name: Publish
    needs: ci
    uses: augentic/pipeline/.github/workflows/publish.yaml@main

  deploy:
    name: Deploy
    needs: publish
    uses: augentic/pipeline/.github/workflows/wasm.yaml@main
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    with:
      package: r9k_adapter
      storage-account: stcredibildemo
      resource-group: rg-credibil-demo
